# Generated by Django 4.2.3 on 2023-08-16 06:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sandr', '0002_products_model_dis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products_model',
            name='product_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='products_model',
            name='product_image',
            field=models.ImageField(db_index=True, upload_to='product_img/'),
        ),
        migrations.AlterField(
            model_name='products_model',
            name='products_name',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
